name: racesense_pulse
description: "Racesense Pulse - social racing app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  intl: ^0.19.0

  # Tracking
  geolocator: ^13.0.1
  sensors_plus: ^5.0.0
  geocoding: ^3.0.0
  flutter_blue_plus: ^1.32.5

  # Mappa OpenStreetMap
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Grafici
  fl_chart: ^0.69.0

  path_provider: ^2.1.4

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_database: ^12.1.0
  shared_preferences: ^2.3.3

  # QR Code Scanner
  qr_code_scanner: ^1.0.1

  # Image picker & sharing
  image_picker: ^1.0.7
  share_plus: ^10.1.4
  permission_handler: ^11.3.0
  url_launcher: ^6.2.5

  # WebView per documenti
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/docs/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/RPICON.png"
  remove_alpha_ios: true
  min_sdk_android: 21
